class Java_Exception9
{
public static void main(String[] args)
{

try
{
int x=4/0;
}
catch(Exception e)
{
System.out.println("Hello");
}
finally
{
System.out.println("Hi");

}


}
}